### ISSUE TITLE
Feature Request: Support initializing PyMuPDFDocument with bytes objects

### ISSUE THREAD

**Issue by Grelo4ka** [conjuncts/gmft_pymupdf#1]
Currently, `PyMuPDFDocument` can only be initialized by providing a file path as a str. Similar libraries, such as pdfplumber, accept multiple data types, like `pathlib.Path`, `BufferedReader` or `BytesIO`. Adding this feature would allow the use of PDF documents directly downloaded as bytes objects, such as those from the web.

**Comment by conjuncts** [comment]
Sounds reasonable -- please let me know if commit ec63abc is sufficient.

**Comment by Grelo4ka** [comment]
Looking good! Thank you for your hard work @conjuncts !
